name: "Bazel Python Package Example"
description: "An example pipeline that builds, tests, and packages a Python library using Bazel."
emoji: ":bazel:"
color: "gray-100"
languages:
  - "Python"
  - "Starlark"
steps:
  - label: ":pipeline:"
    command: "buildkite-agent pipeline upload"
