# template.yml
# Use this as a starting point for your own Buildkite pipeline
name: "Artifacts Pipeline Example"
description: "An example repository you can use as a test project with Buildkite"
steps:
  - label: ":arrow_double_up::package: Generate artifacts"
    command: "./generate_artifacts.sh"

  - wait

  - label: ":arrow_double_down::package: Fetch artifacts"
    command: "./fetch_artifacts.sh"
